apache:
  image: httpd
  ports:
    - 80:80
  volumes:
    - ./web:/usr/local/apache2/htdocs
  container_name: apache
  hostname: apache
  log_driver: "fluentd"
  log_opt:
    fluentd-address: "127.0.0.1:24223"
    fluentd-tag: "docker.apache.{{.Name}}.{{.ID}}"

tomcat:
  build: ./tomcat
  ports:
    - "8888:8080"
  container_name: tomcat
  hostname: tomcat
  log_driver: "fluentd"
  log_opt:
    fluentd-address: "127.0.0.1:24223"
    fluentd-tag: "docker.tomcat.{{.Name}}.{{.ID}}"